let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Casual Shirt",
    price: 45,
    desc: "The Casual Shirt is a versatile and stylish addition to any wardrobe, designed for comfort and ease of wear. Perfect for various occasions, from casual outings to semi-formal events, this shirt combines a modern look with high-quality materials..",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Office Shirt",
    price: 100,
    desc: "The Office Shirt is the perfect blend of style, comfort, and professionalism. Designed for the modern workplace, this shirt ensures you look sharp and feel comfortable throughout your busy day.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "T Shirt",
    price: 25,
    desc: "The T-Shirt is a versatile and comfortable piece of clothing suitable for various occasions. Made from high-quality materials, it offers both style and durability, making it a staple in any wardrobe.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mens Suit",
    price: 300,
    desc: "The Mens Suit is a sophisticated and stylish attire designed for formal occasions, business meetings, and special events. Tailored to perfection, this suit combines elegance and comfort, making it an essential addition to any gentleman's wardrobe.",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Mens Tie",
    price: 25,
    desc: "Elevate your style with our classic Men's Tie, designed to add a touch of sophistication to any outfit. Perfect for formal occasions, business meetings, or any event where you want to make a lasting impression, this tie combines quality craftsmanship with timeless elegance.",
    img: "images/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Casual shoes",
    price: 200,
    desc: "Elevate your everyday style with these Casual Shoes, designed for both comfort and fashion. Perfect for a variety of occasions, from a casual day out to a laid-back evening event, these shoes combine functionality with a trendy design to keep you looking and feeling great all day long.",
    img: "images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "black suit",
    price: 450,
    desc: "The Black Suit is a classic and sophisticated ensemble, perfect for any formal occasion. Crafted from high-quality materials, this suit combines elegance with comfort, ensuring you look your best while feeling at ease.",
    img: "images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "polo shirt",
    price: 45,
    desc: "The Polo Shirt is a classic and versatile piece, perfect for both casual and semi-formal occasions. Made from high-quality, breathable cotton fabric, this shirt ensures maximum comfort and durability.",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "denim shirt",
    price: 85,
    desc: "The Denim Shirt is a timeless fashion staple, offering a blend of style and versatility. Crafted from high-quality denim fabric, this shirt is designed to provide comfort and durability for everyday wear.",
    img: "images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "denim pants",
    price: 120,
    desc: "These Denim Pants are a versatile addition to any wardrobe, offering both style and comfort. Made from high-quality denim fabric, they provide durability for everyday wear. With a classic design and a modern fit, these pants are suitable for various occasions, from casual outings to semi-formal events.",
    img: "images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "basic cap",
    price: 35,
    desc: "The Basic Cap is a timeless accessory designed for everyday wear. Made from high-quality materials, it offers comfort and durability.",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "leather boots",
    price: 350,
    desc: "Crafted for both style and durability, our Leather Boots blend timeless elegance with rugged practicality. Handcrafted from premium leather, these boots exude sophistication while offering exceptional comfort and support for every step.",
    img: "images/img-12.png",
  },
];
